# Generated by Django 4.2.7 on 2024-10-23 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('fecha_vencimiento', models.DateField(auto_now=True)),
                ('fecha_pago', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('monthly_interest', models.FloatField()),
                ('number_of_installments', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('remaining_amount', models.FloatField(null=True)),
                ('remaining_installments', models.IntegerField(null=True)),
                ('loan_type', models.CharField(choices=[('Cuota a rebatir', 'Cuota Rebatir'), ('Cuota fija', 'Cuota Fija'), ('Cuota a vencimiento', 'Cuota Vencimiento'), ('Cuota variable', 'Cuota Variable')], default='Cuota fija', max_length=20)),
                ('monthly_payment', models.FloatField(null=True)),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='juntas.junta')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagosPrestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('custom_amount', models.FloatField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='prestamos.prestamo')),
            ],
        ),
    ]
