# Generated by Django 5.1.1 on 2024-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INSTITUTIONAL', 'Institucional'), ('FACILITATOR', 'Facilitador'), ('DIRECTOR', 'Directivo'), ('PARTNER', 'Socio')], default='PARTNER', max_length=20),
        ),
    ]
