# Generated by Django 4.2.7 on 2024-10-23 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('TARDANZA', 'Tardanza'), ('INASISTENCIA', 'Inasistencia'), ('OTROS', 'Otros')], default='OTROS', max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('junta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='juntas.junta')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
