# Generated by Django 5.1.1 on 2024-10-11 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0004_alter_junta_duration_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='junta',
            name='facilitators',
            field=models.ManyToManyField(blank=True, null=True, related_name='facilitated_juntas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='junta',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juntas.institution'),
        ),
    ]
