# Generated by Django 5.1.1 on 2024-10-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0005_institution_junta_facilitators_junta_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junta',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='junta',
            name='facilitators',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
