# Generated by Django 4.2.7 on 2024-10-23 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accion_purchases', to='juntas.junta')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accion_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
